export const SET_FAVORITE_POPUPS = 'SET_FAVORITE_POPUPS';
export const ADD_FAVORITE_POPUP = 'ADD_FAVORITE_POPUP';
export const REMOVE_FAVORITE_POPUP = 'REMOVE_FAVORITE_POPUP';
export const SET_POPUP_INTEREST_COUNT = 'SET_POPUP_INTEREST_COUNT';
